name: simply_mentions
description: Support mentioning in your project with all the features you need
version: 1.1.0
homepage: https://github.com/ApparyllisOrg/simply_mentions

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diff_match_patch: ^0.4.1
  flutter_markdown: ^0.6.14
  markdown: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.1.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
